apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizationservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthorizationService
  template:
    metadata:
      labels:
        app: AuthorizationService
    spec:
      containers:
      - name: dockersamplerepos
        image: 3acr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: authorizationservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthorizationService

